# Generated by Django 5.2.5 on 2025-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
