# Generated by Django 5.2.5 on 2025-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chat_is_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
