# Generated by Django 5.2.5 on 2025-09-11

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_telegram_chat_id'),
    ]

    operations = [
        # Ensure pgvector extension exists (safe if already installed)
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Ensure the RAG schema exists before creating any tables within it.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS rag;",
            reverse_sql="DROP SCHEMA IF EXISTS rag CASCADE;",
        ),

        migrations.CreateModel(
            name='Doc',
            fields=[
                ('langchain_id', models.TextField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('langchain_metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                # Exact table path including schema; quotes are intentional to keep case/namespace precise
                'db_table': 'rag"."docs',
                'indexes': [
                    pgvector.django.HnswIndex(
                        name='docs_emb_l2_hnsw',
                        fields=['embedding'],
                        opclasses=['vector_l2_ops'],
                        m=16,
                        ef_construction=64,
                    ),
                ],
            },
        ),
    ]


