# Generated by Django 5.2.5 on 2025-09-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_store_kv'),
    ]

    operations = [
        migrations.AddField(
            model_name='storekv',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
