# Generated by Django 5.2.5 on 2025-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_storekv_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='storekv',
            name='ttl_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StoreVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField()),
                ('key', models.TextField()),
                ('field_name', models.TextField()),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph"."store_vectors',
                'indexes': [models.Index(fields=['prefix'], name='store_vectors_prefix_idx')],
                'unique_together': {('prefix', 'key', 'field_name')},
            },
        ),
    ]
