# Generated by Django 5.2.5 on 2025-09-11 21:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_storevector_embedding_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevector',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
