version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - athena

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - ../.env
    volumes:
      - redis_data:/data
    networks:
      - athena

  postgres:
    image: pgvector/pgvector:pg15
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-athena}
      POSTGRES_USER: ${POSTGRES_USER:-athena}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-athena}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athena -d athena"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - athena


  # athena-langchain-public:
  #   build: ../athena-langchain
  #   command: ["bash", "-c", "celery -A athena_langchain.celery worker -Q public -n public_worker@%h --concurrency=1"]
  #   volumes:
  #     - ../athena-langchain:/app
  #   depends_on:
  #     - rabbitmq
  #     - redis
  #     - postgres
  #   env_file:
  #     - ../.env
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://admin:admin@rabbitmq:5672//}
  #     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-rpc://}
  #     - REDIS_HOST=${REDIS_HOST:-redis}
  #     - REDIS_PORT=${REDIS_PORT:-6379}
  #     - DATABASE_URL=${DATABASE_URL:-postgresql://athena:athena@postgres:5432/athena}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   networks:
  #     - athena

  athena-langchain-sensitive:
    build: ../athena-langchain
    command: ["bash", "-c", "watchfiles --filter python 'celery -A athena_langchain.celery worker -Q sensitive -n sensitive_worker@%h --concurrency=1 --pool=solo' /app"]
    volumes:
      - ../athena-langchain:/app
    depends_on:
      - rabbitmq
      - redis
      - postgres
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://admin:admin@rabbitmq:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-rpc://}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql://athena:athena@postgres:5432/athena}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - athena

  athena-drf-worker:
    build: ../athena-DRF
    command: ["bash", "-c", "watchfiles --filter python 'celery -A athena_drf.celery worker -Q gateway -n gateway_worker@%h --concurrency=1 --pool=solo' /app"]
    volumes:
      - ../athena-DRF:/app
    depends_on:
      - rabbitmq
      - redis
      - postgres
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://admin:admin@rabbitmq:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-rpc://}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql://athena:athena@postgres:5432/athena}
    networks:
      - athena

  athena-drf:
    build: ../athena-DRF
    command: ["bash", "-c", "python manage.py makemigrations && python manage.py migrate && watchfiles --filter python 'daphne -b 0.0.0.0 -p 8000 athena_drf.asgi:application' /app"]
    volumes:
      - ../athena-DRF:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - athena-drf-worker
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://admin:admin@rabbitmq:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-rpc://}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql://athena:athena@postgres:5432/athena}
    networks:
      - athena

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:

networks:
  athena:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24